package com.sample
 
import com.hongguaninfo.hgdf.drools.test.DroolsTest.Message;
 
rule "Hello World"
	no-loop true
	salience 1
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
    salience 2
    when
        m : Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "hello cruel world" );
        m.setStatus( Message.HELLO );
        update( m );
end
